title: imhim123469
#logo
description: Roblox all stars BOYYYY 
#show_downloads: true
theme: jekyll-theme-minimal<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Click the Box Game</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <div class="container">
        <h1>Click the Box Game</h1>
        <div id="gameArea">
            <div id="box"></div>
        </div>
        <div class="info">
            <p>Score: <span id="score">0</span></p>
            <p>Time Left: <span id="timeLeft">30</span> seconds</p>
            <button id="startBtn">Start Game</button>
        </div>
    </div>
    <script src="script.js"></script>
</body>
</html>
